import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
	id 'idea'
	id 'java'
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id "org.jetbrains.kotlin.jvm" version "${kotlin_version}"
	id "com.gradleup.shadow" version "9.4.2"
}

version = project.mod_version
group = project.maven_group
loom.log4jConfigs.from "log4j-dev.xml"

base {
	archivesName = project.archives_base_name
}

repositories {
    maven {
        name = "NotEnoughUpdates"
        url = "https://maven.notenoughupdates.org/releases/"
    }
    maven {
        name = "devauth"
        url = "https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1"
    }
    maven {
        name = "Hypixel"
        url = "https://repo.hypixel.net/repository/Hypixel/"
    }
    maven {
        name = "nea89"
        url = "https://repo.nea.moe/releases"
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup("maven.modrinth")
        }
    }
	maven {
		name = "Terraformers"
		url = "https://maven.terraformersmc.com/"
	}
	maven {
		name = "shedaniel"
		url = "https://maven.shedaniel.me"
	}
}

configurations {
	shadowImplementation
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft("com.mojang:minecraft:${project.minecraft_version}")
	implementation("net.fabricmc:fabric-loader:${project.loader_version}")

	// Fabric API. This is technically optional, but you probably want it anyway.
	implementation("net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}")
	implementation("net.fabricmc:fabric-language-kotlin:${project.fabric_kotlin_version}")

	shadowImplementation("org.notenoughupdates.moulconfig:${project.moulconfig_version}")
	shadowImplementation("moe.nea:libautoupdate:${project.libautoupdate_version}")

	include(implementation("com.moulberry:mixinconstraints:${project.mixinconstraints_version}"))
	include(implementation("net.hypixel:mod-api:1.0.2"))

	compileOnly("me.shedaniel:RoughlyEnoughItems-api-fabric:${project.rei_version}") {
		exclude group: "net.fabricmc.fabric-api"
	}

    // Dev Runtimes
	localRuntime("me.djtheredstoner:DevAuth-fabric:${project.devauth_version}")
	localRuntime("maven.modrinth:modmenu:${project.modmenu_version}")
	// we're using modrinth rei and architectury otherwise it imports the wrong architectury version and won't work properly
	localRuntime("maven.modrinth:rei:${project.rei_version}+fabric")
	localRuntime("maven.modrinth:architectury-api:${project.architectury_api}")

	localRuntime("maven.modrinth:hypixel-mod-api:${project.hypixel_mod_api_version}")
	localRuntime("maven.modrinth:sodium:${project.sodium_version}")
	localRuntime("maven.modrinth:no-chat-reports:${project.no_chat_reports_version}")
	localRuntime("maven.modrinth:betterf3:${project.betterf3_version}")
	localRuntime("maven.modrinth:zoomify:${project.zoomify_version}")
	localRuntime("maven.modrinth:cloth-config:${project.cloth_config_version}")
	localRuntime("maven.modrinth:yacl:${project.yacl_version}")

	configurations.shadowImplementation.dependencies.each {
		implementation(it)
	}
}

shadowJar {
	archiveClassifier.set("")
	configurations = [project.configurations.shadowImplementation]

	relocate('io.github.notenoughupdates.moulconfig', 'net.wapic.wpcmod.deps.moulconfig')
	relocate('moe.nea.libautoupdate', 'net.wapic.wpcmod.deps.libautoupdate')

	exclude("META-INF/versions/**")
	mergeServiceFiles()
}

jar {
	archiveClassifier.set("no-deps")
	destinationDirectory.set(rootProject.layout.buildDirectory.dir("badjars"))
}

assemble {
	dependsOn(shadowJar)
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

tasks.withType(KotlinCompile).configureEach {
    compilerOptions {
		jvmTarget = JvmTarget.JVM_25
    }
}

java {
	withSourcesJar()

	toolchain {
		languageVersion.set(JavaLanguageVersion.of(25))
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
            groupId = project.maven_group
            artifactId = project.archives_base_name + "-mc-" + project.minecraft_version
			version = project.mod_version + project.properties.getOrDefault("sha", "")
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		maven {
			name = "WapicMavenRepo"
			url = "https://maven.wapic.net/${project.properties.get("sha") ? "snapshots": "releases"}"
			credentials(PasswordCredentials)
		}
	}
}