import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
	id 'idea'
	id 'java'
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id "org.jetbrains.kotlin.jvm" version "2.1.21"
	id "com.gradleup.shadow" version "9.3.0"
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
    maven {
        name = "NotEnoughUpdates"
        url = "https://maven.notenoughupdates.org/releases/"
    }
    maven {
        name = "devauth"
        url = "https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1"
    }
    maven {
        name = "Hypixel"
        url = "https://repo.hypixel.net/repository/Hypixel/"
    }
    maven {
        name = "nea89"
        url = "https://repo.nea.moe/releases"
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup("maven.modrinth")
        }
    }
    maven { url "https://maven.shedaniel.me" }
}

configurations {
	shadowModImpl
	shadowImpl
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	modImplementation "net.fabricmc:fabric-language-kotlin:${project.fabric_kotlin_version}"

    shadowModImpl "org.notenoughupdates.moulconfig:modern-1.21.10:4.2.0-beta"
	shadowImpl "moe.nea:libautoupdate:1.3.1"

	modImplementation "net.hypixel:mod-api:1.0.1"
    include "maven.modrinth:hypixel-mod-api:1.0.1+build.1+mc1.21"

    modCompileOnly "me.shedaniel:RoughlyEnoughItems-api-fabric:20.0.811"

    // Dev Runtimes
    modLocalRuntime "maven.modrinth:hypixel-mod-api:1.0.1+build.1+mc1.21"
    modLocalRuntime "me.djtheredstoner:DevAuth-fabric:${project.devauth_version}"
    modLocalRuntime "maven.modrinth:sodium:mc1.21.10-0.7.2-fabric"
    modLocalRuntime "maven.modrinth:modmenu:16.0.0-rc.1"
    modLocalRuntime "maven.modrinth:no-chat-reports:Fabric-1.21.10-v2.16.0"

	configurations.shadowModImpl.dependencies.each {
		modImplementation(it)
	}

	configurations.shadowImpl.dependencies.each {
		implementation(it)
	}
}

shadowJar {
	destinationDirectory.set(layout.buildDirectory.dir("badjars"))
	archiveClassifier.set("all-dev")
	configurations = [project.configurations.shadowModImpl] + [project.configurations.shadowImpl]
	exclude("META-INF/versions/**")
	mergeServiceFiles()
	relocate('io.github.notenoughupdates.moulconfig', 'net.wapic.wpcmod.deps.moulconfig')
    relocate('moe.nea.libautoupdate', 'net.wapic.wpcmod.deps.libautoupdate')
}

remapJar {
	archiveClassifier.set("")
	dependsOn shadowJar
	inputFile.set(tasks.shadowJar.archiveFile)
	destinationDirectory.set(rootProject.layout.buildDirectory.dir("libs"))
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

tasks.withType(KotlinCompile).configureEach {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_21
    }
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	archiveClassifier.set("nodeps")
}

tasks.assemble.dependsOn(tasks.remapJar)

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
            groupId = project.maven_group
            artifactId = project.archives_base_name + "-mc-" + project.minecraft_version
			version = project.mod_version + project.properties.getOrDefault("sha", "")
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		maven {
			name = "WapicMavenRepo"
			url = "https://maven.wapic.net/${project.properties.get("sha") ? "snapshots": "releases"}"
			credentials(PasswordCredentials)
		}
	}
}