package net.wapic.wpcmod.features.general

import com.google.gson.Gson
import com.google.gson.GsonBuilder
import io.github.notenoughupdates.moulconfig.ChromaColour
import net.fabricmc.fabric.api.client.message.v1.ClientReceiveMessageEvents
import net.minecraft.network.chat.Component
import net.minecraft.world.entity.Entity
import net.minecraft.world.entity.decoration.ArmorStand
import net.wapic.wpcmod.WpcMod
import net.wapic.wpcmod.config.components.GlowableESPConfig
import net.wapic.wpcmod.features.entity.EspFeature
import net.wapic.wpcmod.util.FileManager
import net.wapic.wpcmod.util.Island
import net.wapic.wpcmod.util.Utils
import net.wapic.wpcmod.util.headTexture
import net.wapic.wpcmod.util.render.state.EntityState
import java.io.File

object CenturyCakeHelper : EspFeature() {

	private val config get() = WpcMod.config.general.centuryCake

	private val EAT_MESSAGE = Regex("^(?:Big )?Yum! You (?:gain|refresh) \\+\\d+. (.+) for 48 hours!$")

	private val eatenCakes = mutableMapOf<CakeType, Long>()
	private const val TWO_DAYS = 172800000

	private val file = File(WpcMod.configDir, "century-cakes.json")
	private val backupFile = File(file.parentFile, "${file.name}.bak")
	private val gson: Gson = GsonBuilder().create()

	fun init() {
		ClientReceiveMessageEvents.GAME.register(::onMessageReceived)
		loadTimes()
	}

	private fun onMessageReceived(message: Component, isActionBar: Boolean) {
		if (isActionBar || Utils.getLocation() != Island.PRIVATE_ISLAND) return

		EAT_MESSAGE.matchEntire(message.string)?.groupValues[1]?.let { stat ->
			WpcMod.LOGGER.debug("Detected Century Cake message with stat: $stat")
			CakeType.entries.find { it.stat == stat }?.let {
				eatenCakes[it] = System.currentTimeMillis() + TWO_DAYS
				WpcMod.LOGGER.debug("Set ${it.name} to ${eatenCakes[it]}")
			}
		}
	}

	override fun compute(entity: Entity): EntityState? {
		if (entity !is ArmorStand) return null

		val cakeType = CakeType.entries.find { it.texture == entity.mainHandItem.headTexture } ?: return null
		eatenCakes[cakeType]?.let { expiration ->
			if (System.currentTimeMillis() < expiration && config.highlightEaten) {
				return EntityState(CakeEatenConfig(config.cakeEatenColor))
			}
		}

		return EntityState(CakeEatenConfig(config.cakeReadyColor))
	}

	override fun isEnabled(): Boolean {
		return Utils.getLocation() == Island.PRIVATE_ISLAND && config.enabled
	}

	private fun loadTimes() {
		val times = FileManager.loadFile<MutableMap<String, Long>>(file, backupFile)
			?: return WpcMod.LOGGER.error("Failed to load century cake times")
		times.forEach { (cakeType, time) ->
			eatenCakes[CakeType.valueOf(cakeType)] = time
			WpcMod.LOGGER.debug("Loaded century cake time for ${cakeType}: $time")
		}
	}

	fun saveTimes() {
		val json = gson.toJson(eatenCakes)
		FileManager.saveFile(json, file, backupFile)
	}

	enum class CakeType(val stat: String, val texture: String) {
		CRAB_COLORED_CENTURY_CAKE(
			"Health",
			"ewogICJ0aW1lc3RhbXAiIDogMTcwODM1MTMzMjczMSwKICAicHJvZmlsZUlkIiA6ICJmOGJmNDBjOWExYzY0ZTllOTIyZTc4M2UwMzNiODBiMyIsCiAgInByb2ZpbGVOYW1lIiA6ICJUeGxvbjUiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjExODU2NzY0MTY2NTNiZjcwNjAzYzcyM2ZmN2E0OGUwODBkYjY0OWE4Y2U1ZDY1YjQ2MWJmNjU0ODc0OTM1YSIsCiAgICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9CiAgfQp9"
		),
		PET_ROCK_CENTURY_CAKE(
			"Defense",
			"ewogICJ0aW1lc3RhbXAiIDogMTYyMjI3MzY1NzM1NCwKICAicHJvZmlsZUlkIiA6ICJjOTAzOGQzZjRiMTg0M2JiYjUwNTU5ZGE3MWFjMTk2MiIsCiAgInByb2ZpbGVOYW1lIiA6ICJUQk5SY29vbGNhdCIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9iYTdiZmE4MGE4NWU3MDdlZWRmOTQ1Yjg4OTA1OTQyZjVmNzc5NWVhNTI2NGQ2OTJhMjJlNzA3ZmM1NzdhODhiIiwKICAgICAgIm1ldGFkYXRhIiA6IHsKICAgICAgICAibW9kZWwiIDogInNsaW0iCiAgICAgIH0KICAgIH0KICB9Cn0="
		),
		FRUIT_CENTURY_CAKE(
			"Strength",
			"ewogICJ0aW1lc3RhbXAiIDogMTY2MDEwMzYwODk2NywKICAicHJvZmlsZUlkIiA6ICI3NTE0NDQ4MTkxZTY0NTQ2OGM5NzM5YTZlMzk1N2JlYiIsCiAgInByb2ZpbGVOYW1lIiA6ICJUaGFua3NNb2phbmciLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTBmMTQ0ZmQ0ZDdjODllMDNmMzVkN2VmZTQxZDM5NzgzOTY4MjM1OTE2YTAwOWU0ZDBmODgyZWMyYzhlNmViNyIKICAgIH0KICB9Cn0="
		),
		POTATO_STYLE_CENTURY_CAKE(
			"Speed",
			"ewogICJ0aW1lc3RhbXAiIDogMTYyMjMwMDI1NDI3MSwKICAicHJvZmlsZUlkIiA6ICIwYTUzMDU0MTM4YWI0YjIyOTVhMGNlZmJiMGU4MmFkYiIsCiAgInByb2ZpbGVOYW1lIiA6ICJQX0hpc2lybyIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9lMjU1ODg5OTliNjc0YjM5OWExOTgwYTI1ZDljYTMyMzYzOWQwMzNlM2Y4NTA0MGMxZGU3ZmZiNDI4YmNhMDk1IiwKICAgICAgIm1ldGFkYXRhIiA6IHsKICAgICAgICAibW9kZWwiIDogInNsaW0iCiAgICAgIH0KICAgIH0KICB9Cn0="
		),
		BARRY_CENTURY_CAKE(
			"Intelligence",
			"ewogICJ0aW1lc3RhbXAiIDogMTcxOTQ1NjgzMDYzNiwKICAicHJvZmlsZUlkIiA6ICJlZGUyYzdhMGFjNjM0MTNiYjA5ZDNmMGJlZTllYzhlYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJ0aGVEZXZKYWRlIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzVlZmYwOTA0ZDVlYzY5MWRkOGUzOGQxZjYzZDM4YmVmMDQ5MjAxM2VjZTkzZDMyYWY5MGRjMDMyMDExNmM1OTciLAogICAgICAibWV0YWRhdGEiIDogewogICAgICAgICJtb2RlbCIgOiAic2xpbSIKICAgICAgfQogICAgfQogIH0KfQ=="
		),
		SEA_EMPEROR_CENTURY_CAKE(
			"Sea Creature Chance",
			"ewogICJ0aW1lc3RhbXAiIDogMTcxOTQ1Njk0MzMwMiwKICAicHJvZmlsZUlkIiA6ICI3MzE4MWQxZDRjYWQ0ZmU0YTcxNWNjNmUxOGNjYzVkNyIsCiAgInByb2ZpbGVOYW1lIiA6ICJaZmVybjRuZGl0byIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9lMTJhMjhlNjlkYTVlNDNjZThmZGVjYzZhODIzYzkyZmZmODQ3MTllMDE0N2NhYWM3MWM1YzhkOTlkYTU3ODFjIiwKICAgICAgIm1ldGFkYXRhIiA6IHsKICAgICAgICAibW9kZWwiIDogInNsaW0iCiAgICAgIH0KICAgIH0KICB9Cn0="
		),
		CENTURY_CAKE_OF_THE_NEXT_DUNGEON(
			"Magic Find",
			"ewogICJ0aW1lc3RhbXAiIDogMTcxOTQ1NjkxMjk0OCwKICAicHJvZmlsZUlkIiA6ICI1ZjU5NmViY2JlOTQ0NmQxYmI0M2JlNGYzZjRiOGJlNSIsCiAgInByb2ZpbGVOYW1lIiA6ICJUZWlsMHNzIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzY0NTkyNzQ2Y2MzNTY3MmVlMjliYjNhMTUzZDc0ZjdhNWQwZTVmZTg2MTI3MjlhMzRmYWQyNTJmZTc5MDQyODMiLAogICAgICAibWV0YWRhdGEiIDogewogICAgICAgICJtb2RlbCIgOiAic2xpbSIKICAgICAgfQogICAgfQogIH0KfQ=="
		),
		LATEST_UPDATE_CENTURY_CAKE(
			"Ferocity",
			"ewogICJ0aW1lc3RhbXAiIDogMTcxOTQ1NzE2MTczOSwKICAicHJvZmlsZUlkIiA6ICI4MDBmNmU2ZGNiMTk0Yzc2OGE1OWU1Y2Q2MzFlNjI2YyIsCiAgInByb2ZpbGVOYW1lIiA6ICJ5dXl1dXUxIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2Y1OGNkMjc1MDg4NDQ3MWMwODM2MzQzMzQzZWM2ZTE4ODIyOWRhMDU0ZWYzNjcxMDEzYWU4ZDQzZDZiMDI1NDgiLAogICAgICAibWV0YWRhdGEiIDogewogICAgICAgICJtb2RlbCIgOiAic2xpbSIKICAgICAgfQogICAgfQogIH0KfQ=="
		),
		STREAMERS_CENTURY_CAKE(
			"Pet Luck",
			"ewogICJ0aW1lc3RhbXAiIDogMTYyMjI5OTg2NzkxMiwKICAicHJvZmlsZUlkIiA6ICJmMjU5MTFiOTZkZDU0MjJhYTcwNzNiOTBmOGI4MTUyMyIsCiAgInByb2ZpbGVOYW1lIiA6ICJmYXJsb3VjaDEwMCIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yNWQ5MjQzYzYxZTJjM2UxZTBmOTkzMTg0M2NhZGJkMGRmZjRhNjQ2MjI1ZWY1NGM1NTc5NzljZjM5YmIyMDU3IiwKICAgICAgIm1ldGFkYXRhIiA6IHsKICAgICAgICAibW9kZWwiIDogInNsaW0iCiAgICAgIH0KICAgIH0KICB9Cn0="
		),
		CHOCOLATE_CENTURY_CAKE(
			"Farming Fortune",
			"ewogICJ0aW1lc3RhbXAiIDogMTY0Nzk1NDY4MzMwMCwKICAicHJvZmlsZUlkIiA6ICJlMmVkYTM1YjMzZGU0M2UxOTVhZmRkNDgxNzQ4ZDlhOSIsCiAgInByb2ZpbGVOYW1lIiA6ICJDaGFsa19SaWNlR0kiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjIzN2NkZmQ3ZDNmMjBlMGY1YjY5N2EyMGM4NTMyNGZiYjdiY2Q0MDllNjUzMzM3Y2NkNWE5Y2U4Y2NhZmMxZCIKICAgIH0KICB9Cn0="
		),
		CLOUDY_CENTURY_CAKE(
			"Foraging Fortune",
			"ewogICJ0aW1lc3RhbXAiIDogMTY0Nzk1NDY0ODIwMCwKICAicHJvZmlsZUlkIiA6ICI4Zjk3NzhmNWVhMTY0MDVmOWEwMDM0YjU4YjljMWM2MCIsCiAgInByb2ZpbGVOYW1lIiA6ICJ1bm5hbWVkYXV0aG9yIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2JhMGE1YjUxMGE4ZDgyNGZmNDkxMGNhNWIyNjk4YWEzZDAzMGY4Mzc4MTBlOGQ3ZjBiYmNhOGNmMDZjZTIwMjMiCiAgICB9CiAgfQp9"
		),
		CENTURY_CAKE_OF_HYPE(
			"Mining Fortune",
			"ewogICJ0aW1lc3RhbXAiIDogMTY0Nzk1NDY2NDEyNywKICAicHJvZmlsZUlkIiA6ICI1MTY4ZjZlMjIyM2E0Y2FjYjdiN2QyZjYyZWMxZGFhOSIsCiAgInByb2ZpbGVOYW1lIiA6ICJkZWZfbm90X2FzaCIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mYjdjZmJiNmFmNzAwZTQ5YmZkYjYwMjM2OTIwYzUyMjA4NGJiODA4YWI2MTI0NzRmYjFmODNlYTQxMGQ1NDg0IgogICAgfQogIH0KfQ=="
		),
		UNDEAD_CENTURY_CAKE(
			"Vitality",
			"ewogICJ0aW1lc3RhbXAiIDogMTY5MjgwNDA3NTczNSwKICAicHJvZmlsZUlkIiA6ICIwYmM5ZDc3YmQ1YTA0NWMzOTY4MWUzYTRhNDIzODZlMyIsCiAgInByb2ZpbGVOYW1lIiA6ICJWaXRvcmlpaW5oYSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9jMzgzMGQyMzVjOWRlNzAzOTQ2ODY0YzI4MWY0MmY5ZDQ1NjQ3NjkxZWUzNTNmYmJiMDcyMjcxNzcwNmI4YmRhIiwKICAgICAgIm1ldGFkYXRhIiA6IHsKICAgICAgICAibW9kZWwiIDogInNsaW0iCiAgICAgIH0KICAgIH0KICB9Cn0="
		),
		NOT_A_LIE_CENTURY_CAKE(
			"True Defense",
			"ewogICJ0aW1lc3RhbXAiIDogMTY5MjgwMzkwNTI0NSwKICAicHJvZmlsZUlkIiA6ICIzNTE2NjhhMTk5MmM0ZGZlOWRkNmY5NTUxNWFkNzVmNyIsCiAgInByb2ZpbGVOYW1lIiA6ICJCbHVlX1BrIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2Q0MGY5Mjk5NTA4Mzg3NjE4Y2ZhZDZkYjM1YzlmNmQ4MDdjNDkzMzdkMzMzZDZlYzNiMTNkOWU4N2QwZDQ4OGYiLAogICAgICAibWV0YWRhdGEiIDogewogICAgICAgICJtb2RlbCIgOiAic2xpbSIKICAgICAgfQogICAgfQogIH0KfQ=="
		),
		RIFT_CENTURY_CAKE(
			"Rift Time",
			"ewogICJ0aW1lc3RhbXAiIDogMTcyOTYxOTQ4NTk3OCwKICAicHJvZmlsZUlkIiA6ICIyYjcyZWYyYWUzMmQ0Zjc1OGEyMThlMDI4MTViYmNjZSIsCiAgInByb2ZpbGVOYW1lIiA6ICJ2b2xrb2RhZl82MyIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kMzdiMWZiNGQwOTgxOTAxYTI5MmM0MmM2NTM5NDZjYTBlMmRlYTE4YmU5Y2FmYTJmMmY5OTMzZmRhYmFhOTg0IiwKICAgICAgIm1ldGFkYXRhIiA6IHsKICAgICAgICAibW9kZWwiIDogInNsaW0iCiAgICAgIH0KICAgIH0KICB9Cn0="
		),
		CORPSE_FLAVORED_CENTURY_CAKE(
			"Cold Resistance",
			"ewogICJ0aW1lc3RhbXAiIDogMTcyOTYxOTM4NjE2NCwKICAicHJvZmlsZUlkIiA6ICIzZGE2ZDgxOTI5MTY0MTNlODhlNzg2MjQ3NzA4YjkzZSIsCiAgInByb2ZpbGVOYW1lIiA6ICJGZXJTdGlsZSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80OThjODhkYWZlMTMzZTc5N2YyOTk0YWNjMDUzYjM5MjZlOTI5MWQwYjcwOTM1OThiMzlkMjcyYzdjOTRhMzY2IiwKICAgICAgIm1ldGFkYXRhIiA6IHsKICAgICAgICAibW9kZWwiIDogInNsaW0iCiAgICAgIH0KICAgIH0KICB9Cn0="
		),
		CENTURY_CAKE_OF_THE_SEVEN_SEAS(
			"Treasure Chance",
			"ewogICJ0aW1lc3RhbXAiIDogMTc4MDkwNjExNTY3NSwKICAicHJvZmlsZUlkIiA6ICI0MDUxNzNiODY0OTM0NTUxOThlOGMzOGJmNmJmNjZiMSIsCiAgInByb2ZpbGVOYW1lIiA6ICJzcGFjZWNhZGV0MTgiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjNkMjIwZjIzNWYyODRmY2M1ZmRjNDVkZGQ5Zjk3ZDY2NjA0ZGEyYTZhZDQxYWI4OTRhNjNmZGU4YjdlNDk5NSIsCiAgICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9CiAgfQp9"
		),
		STARBORN_CENTURY_CAKE(
			"Hunting Fortune",
			"ewogICJ0aW1lc3RhbXAiIDogMTc4MDkwNjE3MzM2MiwKICAicHJvZmlsZUlkIiA6ICI2ZjMzNmQxNzI4ODY0ZTJkOTYxNTFjOGY4YjkzMGFjOCIsCiAgInByb2ZpbGVOYW1lIiA6ICJTVVNfQUoiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjA5MzljYzk4Y2VlMjBkODQ4ODljYTBkY2JjODNlMzVkZjcwYzNjOTgyNDViZjJlNmU2ZjZhM2FkMjg0Y2M3ZSIsCiAgICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9CiAgfQp9"
		),
		LONG_EXPIRED_CENTURY_CAKE(
			"Sweep",
			"ewogICJ0aW1lc3RhbXAiIDogMTc4MDkwNjM0Nzk2OSwKICAicHJvZmlsZUlkIiA6ICIwNTljODIxYzhhODU0NGJiOWJiODVhOGMxNjVhYTc5YiIsCiAgInByb2ZpbGVOYW1lIiA6ICJoZWxsc3RydWNrZWR6IiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzQ1NDVjNmJmZDc3MzAyNDUxMWUyMzVlMTJmNmEyYTJlZGUwNjBjYjhkYmJhOTVlMWZjMjQ1YzE2MDEwNjc2YWIiLAogICAgICAibWV0YWRhdGEiIDogewogICAgICAgICJtb2RlbCIgOiAic2xpbSIKICAgICAgfQogICAgfQogIH0KfQ=="
		),
		HEPHAESTUS_CENTURY_CAKE(
			"Tracking",
			"ewogICJ0aW1lc3RhbXAiIDogMTc4MDkwNjI3Nzk5MywKICAicHJvZmlsZUlkIiA6ICI2NDEwZjRiZjMwNDU0OTdmODBjZDI4NWIyYmJiNTk5NSIsCiAgInByb2ZpbGVOYW1lIiA6ICJNaW5lU2tpbl8xNSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zYjhhM2UyMmQ5N2MwMzFhM2YyZjg3Yzg1ZjgzMWI0YWJmYTQ3MzU4ZDMyNDljYWMwNDNhYmU5OTlmNTQ5YWI2IiwKICAgICAgIm1ldGFkYXRhIiA6IHsKICAgICAgICAibW9kZWwiIDogInNsaW0iCiAgICAgIH0KICAgIH0KICB9Cn0="
		);
	}

	class CakeEatenConfig(override var color: ChromaColour) : GlowableESPConfig() {
		init {
			glow = true
		}
	}
}